検証ができていません
digitech-ymg/renofa-parking-web pull request #111
Opened 2023-02-12 12:25 UTC by YasuiYuya0

@tetsuyanh 
よろしくお願いいたします。

2023-02-20 01:57 UTC, tetsuyanh requested changes
@YasuiYuya0 
指摘しました。

修正と合わせて動作確認まで私の方でやります。

2023-02-20 01:57 UTC, tetsuyanh commented on src/lib/firestore.ts
> +
一旦、後述の関数で事足りるので削除します。

2023-02-20 01:57 UTC, tetsuyanh commented on src/lib/firestore.ts
> +export const Postsdelete = async (
関数名は `deletePost`が良いので変更します。

2023-02-20 01:57 UTC, tetsuyanh commented on src/lib/firestore.ts
> +    where("parkingMinutes", ">", -360)
`where("parkingMinutes", ">", -360)`この条件は冗長なので消します。

2023-02-20 01:57 UTC, tetsuyanh commented on src/lib/firestore.ts
> +  deleteDoc(doc(db, "posts", deletepost));
Firestoreの関数は総じて、Promise<X>を返す必要があります。
（Promiseの説明は追々ということで・・）

このように変更します。
```
return deleteDoc(ref);
```

2023-02-20 01:57 UTC, tetsuyanh commented on src/pages/post.tsx
> +                  Postsdelete(user.id, game.id, parkingId);
Promiseを返す関数は非同期で動きます。
async/awaitを適用しますね。

2023-02-20 02:41 UTC, tetsuyanh approved these changes

2023-02-22 01:04 UTC, merged

2023-02-22 01:05 UTC, YasuiYuya0 commented
確認できました～！
丁寧な解説、修正ありがとうございます！