メインページの表示をオフシーズンかどうかで自動的に切り替えるように変更
digitech-ymg/renofa-parking-web pull request #115
Opened 2023-03-15 15:12 UTC by UramotoKazushi

・前の試合と次の試合の日付の差が30日以上なら、オフシーズンと判定する関数を追加。
・通常（オフシーズンではない）の場合、通常通り駐車場情報等を表示させる
・オフシーズンの場合、振り返りコンテンツを表示させ、駐車場情報等は表示させない

2023-03-19 12:32 UTC, tetsuyanh requested changes
@UramotoKazushi 
指摘いれました。
すいません、オフシーズンの判定、作り直しに近いかと思います。。

2023-03-19 12:32 UTC, tetsuyanh commented on src/lib/firestore.ts
> +export const getNextGame = async (): Promise<Game> => {
私の方で要件としては、
**現在日時と直近の次の試合まで30日開く場合はオフシーズン**としていました。
きちんとした仕様を伝えてきれてないための誤解だと思うので、
大変すいません。。

例えばシーンズンのアウトとインはこのようなイメージです。

・現在10月20日、次の試合10月27日（当期の最終戦）
　10月27日の試合表示＆投稿可能（オンシーズン）

・現在10月28日、次の試合がない（次期スケジュール未発表）
 　振り返りページ（オフ）

・現在1月15日、次の試合2月16日（次期の開幕戦）
　振り返りページ（オフ）

・現在1月16日、次の試合2月16日（次期の開幕戦）
　2月16日の試合表示＆投稿可能（オンシーズン）

既に直近の試合を取得する関数`getMostRecentGame`があるため、
このコミットで追加していただいた`getPreviousGame`と`getNextGame`は不要かと想います。

2023-03-19 12:32 UTC, tetsuyanh commented on src/lib/firestore.ts
> +  const nextGame = await getNextGame();
現在日と（次の）試合日を投げて、オン/オフシーズンを判定する関数は賛成です。

ただし、関数内部でDB操作はせずに、引数として2つの日付を受け取るのが良いです。
となるとこの関数は、`lib/firestore.ts`の中にあるべきではなく、
`lib/game.ts`や`utils/game.ts`というファイルにあるのが自然になります。

そして、DB操作が不要なので関数の単体テストを書きたいです。
テストは`utils/user.spec.ts`を参考にしてください。

2023-03-19 12:32 UTC, tetsuyanh commented on src/pages/index.tsx
> +  });
直近の試合が取得出来次第、シーズンイン/オフの判断をして、
`isOffSeason`のPropsを更新するのが良さそうです。

こういうのはどうでしょうか？
```ts
// オフシーズン変数Props（確定前はundefinedで何も表示させない）
const [offSeason, setOffSeason] = useState<boolean | undefined>(undefined);

// game更新時にオフシーズン変数更新
useEffect(() => {
  if (game) {
    // オフ判定
    setOffSeason(isOffSeason(game.startAt, new Date())
  } else {
  // 試合がない＝オフ
    setOffSeason(false);
  }
}, [game])
```

2023-03-19 12:32 UTC, tetsuyanh commented on src/pages/index.tsx
> +      {!offSeason && (
オンシーズンはこうなります。
`!offSeason`だと`undefined`もfalsy値として含んでしまい、試合情報取得前に画面表示がされてしまいます
```
{offSeason === false &&
```

2023-04-24 16:37 UTC, UramotoKazushi commented on src/lib/firestore.ts
> +export const getNextGame = async (): Promise<Game> => {
`getPreviousGame`と`getNextGame`、`isOffSeason`は削除します。
`isOffSeasion`については、utils直下のgame.tsに作成するようにします。

2023-04-24 16:40 UTC, UramotoKazushi commented on src/lib/firestore.ts
> +  const nextGame = await getNextGame();
`utils/game.ts`案を採用させていただきました。
また、`utils/user.spec.ts`を参考に、`game.spec.ts`を作成しています。

2023-04-24 16:41 UTC, UramotoKazushi commented on src/pages/index.tsx
> +  });
ありがとうございます。こういう作り方は思いつきませんでした。このまま利用させていただきます！

2023-04-24 16:42 UTC, UramotoKazushi commented on src/pages/index.tsx
> +      {!offSeason && (
undefinedも含んでしまう件、存じ上げてませんでした。
ありがとうございます。上記の通り`{offSeason === false &&`とするよう修正しました。

2023-04-28 12:32 UTC, tetsuyanh requested changes
@UramotoKazushi Web周りはOKです。オフシーズン判定の関数でいくつか指摘入れました。

2023-04-28 12:32 UTC, tetsuyanh commented on src/utils/game.ts
> +export const isOffSeason = (date1: Date, date2: Date): boolean => {
「今日」と「次の試合の日」というのが引数名で分かった方が良いと思いました。
`(today: Date, nextGameDay: Date)`

2023-04-28 12:32 UTC, tetsuyanh commented on src/utils/game.ts
> +  return false;
`return diffInDays >= 30`で良いかと思います。

2023-04-28 12:32 UTC, tetsuyanh commented on src/utils/game.spec.ts
> +    const date2 = new Date("2023-02-01");
コピペしたままなのか、年度を跨いだテストになっていません。

2023-04-28 12:32 UTC, tetsuyanh commented on src/utils/game.spec.ts
> +    const date2 = new Date("2023-01-30");
引数で指摘したように、テストの引数も`today`と`next`（省略）みたいな変数名がいいと思いました。

2023-04-28 12:32 UTC, tetsuyanh commented on src/utils/game.ts
> +  const diff = Math.abs(date2.getTime() - date1.getTime());
次の試合が過去の日を渡されることも可能性としてはあるかと思います、
その時に絶対値（30日以内の過去の試合）だと困るので、普通に「次の試合ー今日」という引き算が良いと思いました。
`nextGameDate.getTime() - today.getTime()`

> 次の試合が過去の日を渡される

このケースもテストに加えて欲しいです。（現コードだとこのケースのテストがコケます）

2023-05-01 13:19 UTC, UramotoKazushi commented on src/utils/game.ts
> +  const diff = Math.abs(date2.getTime() - date1.getTime());
こちらで記載したほうが良かったですね、以下の通りのパターンであってるか、確認いただきたいです。

![image](https://user-images.githubusercontent.com/110393751/235457010-d2b4a4ce-5409-46fb-a0ed-afc86f219097.png)

2023-05-02 06:55 UTC, tetsuyanh approved these changes

2023-05-02 06:56 UTC, tetsuyanh commented
@UramotoKazushi 
OKです。お疲れ様でした。マージしておきます！

2023-05-02 06:56 UTC, merged