説明ページ実装
digitech-ymg/renofa-parking-web pull request #19
Opened 2021-11-15 03:28 UTC by geardigital

#10 実装しました

2021-11-15 04:14 UTC, geardigital commented
![スクリーンショット 2021-11-15 130211](https://user-images.githubusercontent.com/90988949/141721066-540a8157-954d-4859-9097-6dfc9c774f15.png)

キャプチャのところですが、ローカルでは縦並びになっていましたが、サーバーでは`<Flex flexDirection="column">`が効かずに横並びになってしまいます。

2021-11-15 06:29 UTC, tetsuyanh commented
@watagit @geardigital 修正コミット積みました。

2021-11-18 12:29 UTC, watagit requested changes

2021-11-18 12:29 UTC, watagit commented on src/pages/about.tsx
> +    <Container my={8}>
![must](https://img.shields.io/badge/review-must-red)
なるべく Figma のレイアウトに寄せたいので、背景色と文字色は逆でお願いします！ 👍 
```suggestion
    <Container py={8} bgColor="white" color="black">
```

2021-11-18 23:08 UTC, geardigital commented
背景色と文字色を修正しました。
よろしくお願いします。

2021-11-20 01:47 UTC, watagit approved these changes

2021-11-21 01:20 UTC, merged