【WIP】環境構築
digitech-ymg/renofa-parking-web pull request #5
Opened 2021-11-05 01:43 UTC by nishidayoshikatsu

2021-11-05 05:49 UTC, tetsuyanh requested changes
@nishidayoshikatsu 
1つ質問です。
`Dockerfile` ファイルを用意してないのは、とりあえずコマンド一発で済んでるからですかね？

2021-11-07 02:19 UTC, nishidayoshikatsu commented
> @nishidayoshikatsu 1つ質問です。 `Dockerfile` ファイルを用意してないのは、とりあえずコマンド一発で済んでるからですかね？

@tetsuyanh 
返信遅れてすみません。そうですね。node環境でyarn installすればいいだけなので特段必要ないかなと思っていたのですが、あった方がいいですかね？
あった方が良さそうであれば追加します（先に他のissueを片付けておきます）

2021-11-07 03:06 UTC, tetsuyanh commented
@nishidayoshikatsu 
いえ、大丈夫です。approveします！
マージは当人が良いかなと。会議で話しましょうー。

2021-11-07 03:06 UTC, tetsuyanh approved these changes

2021-11-07 03:08 UTC, nishidayoshikatsu commented
@tetsuyanh 
ありがとうございます！
マージします！

2021-11-07 03:09 UTC, merged